name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Install Dependencies
      run: yarn

    - name: Build
      run: yarn build

    - name: Deploy
      uses: appleboy/scp-action@master
      with:
        host: mirocosic.com
        username: github
        password: ${{ secrets.GITHUB_USER_PASS }}
        port: 22
        source: "build/*"
        target: "/var/www/mirocosic.com.com"
