name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Install Dependencies
      run: yarn

    - name: Build
      run: yarn build

    - name: Deploy
      uses: horochx/deploy-via-scp@v1.0.1
      with:
        local: build # eg: dist
        remote: /var/www/mirocosic.com.com # eg: /home/github-action
        host: mirocosic.com # eg: example.com
        port: 22 # eg: 22
        user: github # eg: github-action
        key: ${{ secrets.GITHUB_KEY }} 


    #- name: Deploy
    #  run: sshpass -p "${{ secrets.GITHUB_USER_PASS }}" scp -r build/* github@mirocosic.com:/var/www/mirocosic.com.com
